#output "ip" {
#  value = "${aws_route53_record.srehan-httpd.dns_name}"
#}

#output "alias_name" {
#  value = tolist(aws_route53_record.srehan-httpd.alias.*.name)[0]
#}

output "elb-dns" {
  value = aws_elb.SkyDemo-elb.dns_name
}

output "SkyDemo_ip" {
  value = [aws_instance.SkyDemo.*.private_ip]
}


output "SkyDemo_ip_public" {
  value = [aws_instance.SkyDemo.*.public_ip]
}


output "SkyDemo_name" {
  value = [aws_instance.SkyDemo.*.tags.Name]
}

output "ssh_key" {
  description = "ssh key generated by terraform"
  value       = tls_private_key.skydemo.private_key_pem
  sensitive   = true
}
